services:
  client:
    image: node:22-alpine
    container_name: pinguiz-client
    working_dir: /client
    command: sh -c "rm -rf ./node_modules && npm install && npm run prod"
    volumes:
      - ./client:/client
    networks:
      - pinguiz-net
    stop_grace_period: 1s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.services.client.loadbalancer.server.port=4173"
      - "traefik.http.routers.client.tls=true"

  server:
    image: oven/bun:1-alpine
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - server/env/.env.dev
    networks:
      - pinguiz-net
    command: >
      sh -c "
        until nc -z pinguiz-sql 3306; do
          echo '⏳ Attente de MariaDB...';
          sleep 2;
        done &&
        echo '✅ MariaDB prêt, lancement du serveur' &&
        bun install &&
        bun --watch src/app.ts
      "
    depends_on:
      - pinguiz-sql
    stop_grace_period: 1s
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.services.server.loadbalancer.server.port=3000"
      - "traefik.http.routers.server.tls=true"

  pinguiz-sql:
    image: mariadb:11.7.2
    container_name: pinguiz-sql
    environment:
      MYSQL_ROOT_PASSWORD: '%9689I%t9j6RC#Hbn6'
    ports:
      - "3306:3306"
    volumes:
      - ./server/env/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - master-data:/var/lib/mysql
      - ./master/fichiers-mysql:/var/lib/mysql-files/
    command: --server-id=1 --log-bin=mysql-bin --log-bin-index=mysql-bin.index --relay-log=relay-bin --relay-log-index=relay-bin.index
    networks:
      - pinguiz-net

  traefik:
    image: traefik:v3.4.0
    container_name: pinguiz-traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    networks:
      - pinguiz-net
    depends_on:
      - client
      - server
    labels:
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  pinguiz-net:
    driver: bridge

volumes:
    master-data: