services:
    client:
        container_name: pinguizz-client
        build: client/
        ports:
            - "4200:4200"
        working_dir: /app
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:3000
        networks:
            - pinguizz-net
        stop_grace_period: 1s
    server:
        image: oven/bun:1-alpine
        container_name: pinguizz-server
        working_dir: /app
        ports:
            - "3000:3000"
        volumes:
            - ./server:/app
        env_file:
            - server/env/.env.dev
        networks:
            - pinguizz-net
        command: "sh -c 'bun --watch src/app.ts'"
        depends_on:
            - mysql
        stop_grace_period: 1s
        restart: always

    mysql:
        image: mysql:8
        container_name: pinguizz-sql
        env_file:
            - server/env/.env.dev
        volumes:
            - ./server/env/sql/initUser.sql:/docker-entrypoint-initdb.d/init.sql
            - db-data-pinguizz:/var/lib/mysql
        networks:
            - pinguizz-net
        stop_grace_period: 1s
    phpmyadmin:
        image: phpmyadmin:5
        container_name: pinguizz-pma
        ports:
            - "8080:80"
        env_file:
            - server/env/.env.dev
        networks:
            - pinguizz-net
        depends_on:
            - mysql
        stop_grace_period: 1s
networks:
    pinguizz-net:
        driver: bridge

volumes:
    db-data-pinguizz: {}
