services:
    client:
        build: ./client
        container_name: pinguiz-client
        working_dir: /app
        ports:
            - "5173:5173"
        # ⛔️ ENLÈVE cette ligne ↓ car elle relance npm install et provoque les conflits
        # command: sh -c "npm install && npm run dev"
        volumes:
            - ./client:/app       # ✅ tu peux garder ce volume pour le hot reload
        environment:
            - VITE_API_URL=http://localhost:3000
        networks:
            - pinguiz-net
        stop_grace_period: 1s
    server:
        image: oven/bun:1-alpine
        container_name: pinguiz-server
        working_dir: /app
        ports:
            - "3000:3000"
        volumes:
            - ./server:/app
        env_file:
            - server/env/.env.dev
        networks:
            - pinguiz-net
        command: "sh -c 'bun --watch src/app.ts'"
        depends_on:
            - mysql
        stop_grace_period: 1s
        restart: always

    mysql:
        image: mysql:8
        container_name: pinguiz-sql
        env_file:
            - server/env/.env.dev
        volumes:
            - ./server/env/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - db-data-pinguiz:/var/lib/mysql
        networks:
            - pinguiz-net
        stop_grace_period: 1s
    phpmyadmin:
        image: phpmyadmin:5
        container_name: pinguiz-pma
        ports:
            - "8080:80"
        env_file:
            - server/env/.env.dev
        networks:
            - pinguiz-net
        depends_on:
            - mysql
        stop_grace_period: 1s
networks:
    pinguiz-net:
        driver: bridge

volumes:
    db-data-pinguiz: {}
