ALTER USER 'root'@'%' IDENTIFIED BY '%9689I%t9j6RC#Hbn6';

DROP USER IF EXISTS 'Rudy'@'%';

CREATE USER 'Rudy'@'%' IDENTIFIED BY '6y!Sj5G&&hHcugRR8t&';

GRANT ALL PRIVILEGES ON abyss.* TO 'Rudy'@'%';
GRANT CREATE, DROP, ALTER, INDEX, CREATE TEMPORARY TABLES, CREATE USER ON *.* TO 'Rudy'@'%';

FLUSH PRIVILEGES;